import face.models.models as models
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    args = 'none'
    help = 'Wipes out all instances of a particular template so that they can be regenerated by the parseall script.'

    def handle(self, *args, **options):
        template = models.QuestionTemplate.objects.get(id=args[0])
        # TODO: Can the two excludes be merged?
        questions = models.UserQuestion.objects.exclude(status='solved').exclude(status='retired').filter(template=template)
        question_instances = models.QuestionInstance.objects.exclude(active=False).filter(template=template)
        
        print 'Purging all unsolved instances of template #%d...' % template.id
        print '  %d target instances found.' % len(questions)

        # Deactivate all QuestionInstances for this particular template.
        for instance in question_instances:
            instance.active = False
            instance.save()

        # Retire all UserQuestions that are tied to the template.
        for question in questions:
            question.status = 'retired'
            question.save()
        
        template.status = 'waiting'
        template.save()
        
        print 'Done.'