import face.models.models as models
import sys

from django.core.management.base import BaseCommand

class Command(BaseCommand):
    args = 'none'
    help = 'Wipes out all instances of a particular template so that they can be regenerated by the parseall script.'

    def handle(self, *args, **options):
        try:
            # The default owner is user #1.  This should probably be changed but 
            # I'm not sure what the right way to do it is.
            owner = models.User.objects.get(id=1)
        except models.User.objects.DoesNotExist:
            print "Please initialize your database before running this command (python manage.py syncdb)"
            print "You must create a superuser to host the first account."
            sys.exit(1)

        league_name = raw_input('Please provide a name for your first league: ')
        league = models.RegisLeague(name=league_name, owner=owner)

        league.save()
        print "Created a new league with ownership belonging to '%s'" % owner.username

        #league.save()
